export const PAGE_SIZE = 8;
export const LIGHT_MODE = "light",
	DARK_MODE = "dark",
	SYSTEM_MODE = "system";
export const DEFAULT_THEME = LIGHT_MODE; 
export const WALLPAPER_BANNER = "banner",
	WALLPAPER_OVERLAY = "overlay",
	WALLPAPER_NONE = "none";
export const BANNER_HEIGHT = 35;
export const BANNER_HEIGHT_EXTEND = 30;
export const BANNER_HEIGHT_HOME = BANNER_HEIGHT + BANNER_HEIGHT_EXTEND;
export const MAIN_PANEL_OVERLAPS_BANNER_HEIGHT = 3.5;
export const PAGE_WIDTH = 90;
export const UNCATEGORIZED = "uncategorized";
